env:
  commonjs: true
  es6: true
  node: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  "@typescript-eslint/no-unused-vars":
    - warn
    - args: none
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreVoid: true
